### ISSUE TITLE
/ratings crashes when there are no games in current period

### ISSUE THREAD

**Issue by gugi9000** [gugi9000/foosball#58]
`GET /ratings text/html:
    => Matched: GET /ratings
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(2, Null)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
GET / text/html:
    => Matched: GET /
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
`

**Comment by gugi9000** [comment]
if no games in current period the controller should return a mock set of data instead of .. whatever it does..

**Comment by gugi9000** [comment]
`developmenttsv()` is fixed, but not `ratings()`
